@echo off

echo //
echo // !! DO NOT EDIT THIS FILE
echo // Generated by PreBuild_GenerateAssemblyInfoVersionPart.cmd
echo // 
echo using System.Reflection;
echo [assembly: MacFace.FloatApp.ApplicationVersionString("%DATE:/=-% (ƒAƒ‹ƒtƒ@”Å)")]
